### PR TITLE
add Scalingo in new PaaS > Europe section

### PR DESCRIPTION
**Pull request by yannski**

### CODE REVIEW

**Comment by dexteryy** [comment]
China section is a very special case. It has [the toughest Internet censorship policies](https://en.greatfire.org/analyzer) and [the most powerful national firewall technology](https://blog.thousandeyes.com/deconstructing-great-firewall-china/) in the world. All global cloud computing vendors can not provide their services directly within China. In short,  the Internet is broken into two isolated parts -- the global internet and the China internet. So for the cloud service resources, it's necessary to provide a China section.

But for Europe or other regions, that is different. They are in the same global competitive environment. Since I need to keep only "one or a few" links for each nested "category", Scalingo can not be included unless it is as popular as heruko or now, or very different from them, for the global community.

**Comment by yannski** [comment]
Hi,
From (some) european developers, choosing a provider registered in Europe is important, especially for data privacy reason (think about PRISM and the Patriot Act for example).

**Comment by dexteryy** [comment]
@yannski This document focuses on the pragmatism and the technology itself. Try to reflect common technology and technological advance. We can have another document (e.g. an awesome list) to ease the worry about data privacy or satisfy the needs of commercial promotion.

**Comment by marlazinger200** [comment]
1

**Pull request closed without merging**
